version: "3.4"
services:
  printserver:
    build: .
    restart: unless-stopped
    environment:
      PRINTER_ID: Paperless_Printer # ID (No spaces)
      PRINTER_NAME: Paperless Printer # Name of printer
      HOSTNAME: '192.168.0.12:631' # Use static IP (below) or hostname if you have one
      OUTPUT_SUBPATH: 'vprint' # Subpath in /mnt/output/
    networks:
      cups-vlan:
        ipv4_address: 192.168.8.12 # modify as necessary
    # Alternatively, use host networking (and comment out networks section above)
    # network_mode: host
    ports:
      - 631:631 # Expose HTTP server (Or use a reverse proxy)
    volumes:
      - /tmp/output:/mnt/output

networks:
  cups-vlan:
    driver: macvlan
    driver_opts:
      parent: eth0 # Update as necessary
    ipam:
      config:
        - subnet: "192.168.0.0/24"
          ip_range: "192.168.0.12/32" #static IP
          gateway: "192.168.0.1"
